import { socketsContext } from "@/contexts/socketcontext";
import { useContext } from "react";

const {
  friends2,
  setfriends,
  pendingfriendinvitations,
  setpendingfriendinvitations,
  onlineusers,
  setonlineusers,
  targetmailaddress,
  settargetmailaddress,
  Connectwithsocketserver,
  newSocket,
  setNewSocket,
  isuserinroom,
  setisuserinroom,
  isusercreator,
  setisusercreator,
  Roomdetails,
  setRoomdetails,
  activerooms,
  setactiverooms,
  localstream,
  setlocalstream,
  remotestreams,
  setremotestreams,
  audioonly,
  setaudioonly,
  screensharingstream,
  setscreensharingstream,
  isscreensharingactive,
  setisscreensharingactive,
  openroom,
  setopenroom,
  videodisplay,
  setvideodisplay,
} = useContext(socketsContext);

